### ISSUE TITLE
Create the Backstage secret

### ISSUE THREAD

**Issue by amiable-dev** [amiable-dev/backstage-kubernetes-hosting#11]
For any Backstage configuration secrets, such as authorization tokens, we can create a similar Kubernetes Secret as we did [for PostgreSQL](https://backstage.io/docs/deployment/k8s#creating-a-postgresql-secret), remembering to base64 encode the values:

``` yaml
# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: VG9rZW5Ub2tlblRva2VuVG9rZW5NYWxrb3ZpY2hUb2tlbg==
```

Apply the secret to the Kubernetes cluster:

``` bash
$ kubectl apply -f kubernetes/backstage-secrets.yaml
secret/backstage-secrets created
```
