### ISSUE TITLE
Create a Kubernetes secret for the Postgres username and passord

### ISSUE THREAD

**Issue by amiable-dev** [amiable-dev/backstage-kubernetes-hosting#3]
Create a Kubernetes Secret for the PostgreSQL username and password.. This will be used by both the PostgreSQL database and Backstage deployments:

```yaml
# kubernetes/postgres-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_USER: YmFja3N0YWdl
  POSTGRES_PASSWORD: aHVudGVyMg==
```

The data in Kubernetes secrets are base64-encoded. The values can be generated on the command line:

``` bash
$ echo -n "backstage" | base64
YmFja3N0YWdl
```

The secrets can now be applied to the Kubernetes cluster:

``` bash
$ kubectl apply -f kubernetes/postgres-secrets.yaml
secret/postgres-secrets created
```
